// app/layout.jsx or wherever your layout is located
"use client"
import "./globals.css";
import CustomNavbar from "@/Shared/CustomNavbar";
import Footer from "@/Shared/Footer";
import { Roboto } from 'next/font/google';
import { usePathname } from "next/navigation";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

// export const metadata = {
//   title: "Speach and Langauge Tharapy",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  const pathname = usePathname();

  const isDeshboard = pathname.startsWith('/Deshboard')

  return (
    <html lang="en" className={roboto.variable}>
      <body className="antialiased font-roboto">
        <div className="flex flex-col min-h-screen">
          {!isDeshboard && <CustomNavbar />}
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
