// app/layout.jsx or wherever your layout is located
import "./globals.css";
import CustomNavbar from "@/Shared/CustomNavbar";
import Footer from "@/Shared/Footer";
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className="antialiased font-roboto">
        <div className="flex flex-col min-h-screen">
          <CustomNavbar />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
